server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # This line is crucial for React Router:
        # It tells Nginx to send all requests to index.html 
        # so the JavaScript code can handle the routing.
        try_files $uri $uri/ /index.html;
    }
}